CREATE WAREHOUSE IF NOT EXISTS WH_ETL
  WITH WAREHOUSE_SIZE='XSMALL'
  WAREHOUSE_TYPE='STANDARD'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE;

CREATE DATABASE IF NOT EXISTS ECOM;

CREATE SCHEMA IF NOT EXISTS ECOM.RAW;  
CREATE SCHEMA IF NOT EXISTS ECOM.STG;  
CREATE SCHEMA IF NOT EXISTS ECOM.MART; 

 